/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UilArrowRight: typeof import('~icons/uil/arrow-right')['default']
    UilDownloadAlt: typeof import('~icons/uil/download-alt')['default']
    UilFileAlt: typeof import('~icons/uil/file-alt')['default']
    UilFileExport: typeof import('~icons/uil/file-export')['default']
    UilFolderTimes: typeof import('~icons/uil/folder-times')['default']
    UilHomeAlt: typeof import('~icons/uil/home-alt')['default']
    UilInfoCircle: typeof import('~icons/uil/info-circle')['default']
    UilMoon: typeof import('~icons/uil/moon')['default']
    UilPen: typeof import('~icons/uil/pen')['default']
    UilPlus: typeof import('~icons/uil/plus')['default']
    UilRefresh: typeof import('~icons/uil/refresh')['default']
    UilSun: typeof import('~icons/uil/sun')['default']
    UilTrash: typeof import('~icons/uil/trash')['default']
    UilUpload: typeof import('~icons/uil/upload')['default']
    VLogo: typeof import('./components/VLogo.vue')['default']
    VNav: typeof import('./components/VNav.vue')['default']
  }
}
